### ISSUE TITLE
"Error encountered during back-translation of rps19"

### ISSUE THREAD

**Issue by tkn132** [michaelgruenstaeudl/StandardizedPlastidPhylogenomics#1]
Hello, 

Thanks very much for your great workflow. 

I am doing the Phylogenetic analysis on 25 orchids' chloroplast genomes using your Script09.py. I got the following errors and then it stopped working. Could you please guide me on how to fix this? Thanks!

`BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
  ERROR: Error encountered during back-translation of rps19
  ERROR: Cannot process alignment of rps19`

**Comment by michaelgruenstaeudl** [comment]
Hi tkn132,
the warnings and errors you listed indicate some problems with the annotations of gene `rps19` in your input genomes. Here are the details:

The warning `BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future` indicates that one of the coding sequences is not a multiple of three. This will not terminate the script, but you should check the annotations nonetheless, as coding sequences that are not a multiple of three are probably the result of incorrect annotations. In all likelihood, the problem rests with the length of gene `rps19` (or the combined length of exon 1 and exon 2, if `rps19` in orchids were spliced) not being a multiple of three.

The errors `ERROR: Error encountered during back-translation of rps19` and `ERROR: Cannot process alignment of rps19` indicate that the back-translation from amino acids to nucleotides could not be conducted. This error is indicative either for annotations that are too short (i.e., only a a handful of nucleotides present) or for alignments that contain sequences only of one or two taxa. To resolve this issue, I would suggest that you look at the annotations of `rps19` in your input genomes regarding presence, length and orientation of the annotations.

Best, Michael G.
